[package]
name = "micro-sentiment"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.0"
rust-bert = "0.20"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
